### ISSUE TITLE
javascripting-jpについて

### ISSUE THREAD

**Issue by kohei-takata** [nodeschool-jp/translators#4]
javascripting-jpをやってて気づいたんですが、翻訳のためのFork後に本家のほうに項目が１つ追加されているような気がします。
こちらも翻訳したほうがいいですかね？

https://github.com/sethvincent/javascripting/pull/61

**Comment by tai2** [comment]
あ、ほんとだ。配列へのアクセスが追加されてますね。
追加できたらいいですね。

**Comment by ledsun** [comment]
本家に新しい課題が増えたこと、認識しました。
nodeschoolまでに、対応する時間が取れるかはちょっとわかりません。
プルリクエスト歓迎です。

**Comment by ledsun** [comment]
とりあえずこちらのリポジトリでissueとbranch切りました。
https://github.com/ledsun/javascripting/issues/14

**Comment by tai2** [comment]
:+1:

**Comment by kohei-takata** [comment]
@ledsun :+1: 

じゃあ、言い出しっぺの法則で僕がやります！
終わったら、切っていただいたブランチの方にPR送りますね

**Comment by ledsun** [comment]
:+1: 
お願いします。

**Comment by sotayamashita** [comment]
お願いします

**Comment by kohei-takata** [comment]
訳してPRを送りました！
確認お願いします〜
https://github.com/ledsun/javascripting/pull/15

**Comment by ledsun** [comment]
マージ & パブリッシュしました。

**Comment by kohei-takata** [comment]
:+1:

**Comment by kohei-takata** [comment]
翻訳完了ということでcloseします。
