### ISSUE TITLE
nodeschool-jp より良い名前

### ISSUE THREAD

**Issue by tgfjt** [nodeschool-jp/translators#5]
nodeschool-jp だと、日本独自のものであるような印象、閉塞的な印象を与えるのでは。
nodeschool-ja の方が、言語別であり、翻訳用であることがわかりやすくて良いのでは。

というご意見を頂きました。
確かにその通りと思います。

@nodeschool-jp/translators 

改名しちゃっても良いでしょうか？
または他のご意見ありますでしょうか？

お手数おかけしますが、よろしくお願い致します！

**Comment by tai2** [comment]
なるほど。言われてみると、そういう観点からはjpよりjaのほうがすこしマシですね。
主に外国の方に対する配慮だと思いますので、organizationの説明文についても英文を併記してみては?

**Comment by tgfjt** [comment]
@tai2 
あーそうですね、翻訳グループですよ的な英文あると良いですね。

あとは、翻訳というか活動のロードマップなんかがあると良いようです。
https://gist.github.com/tdd/d7b2b719485cdf87bd5f

**Comment by kohei-takata** [comment]
改名してもいいと思います！
また、説明文に関してもあったほうがいいと思います！

**Comment by tako-black** [comment]
改名してもいいと思います！
また、説明文に関してもあったほうがいいと思います！

**Comment by tgfjt** [comment]
あんまり英文自信ないですが。こんな感じでしょうか？
This is a translation group for NodeSchool's workshops.

**Comment by tai2** [comment]
:+1:

**Comment by kohei-takata** [comment]
This is a translation group for NodeSchool's workshops to Japanese.
「日本語に翻訳する」みたいな
僕も英文自信ないですが。。。

**Comment by tgfjt** [comment]
ああ、いいですね、Japanese大事なとこですね。

**Comment by tgfjt** [comment]
なんか長いですが、説明文は変更してみました！

**Comment by sotayamashita** [comment]
@tgfjt 閉鎖的だと捉えられてしまうのであれば、改名しても良いと思います。

**Comment by sotayamashita** [comment]
> This is a translation group for NodeSchool's workshops to Japanese.

↓

Translation group for NodeSchool's workshops to Japanese.

でもいいと思います。

**Comment by ledsun** [comment]
translationとJapaneseをなるべく前に移動して

A translation of NodeSchool's workshops into Japanese is the aim of this organization.

はどうでしょうか？

**Comment by tgfjt** [comment]
@ledsun ありがとうございます！取り込ませて頂きました！

**Comment by tgfjt** [comment]
@nodeschool-jp/translators

改名問題なさそうなので、念のため明日まで待って nodeschool-ja に renameします。

**Comment by sotayamashita** [comment]
@tgfjt よろしくお願いします。 :+1:

**Comment by tgfjt** [comment]
@nodeschool-ja/translators 
リネームしました。
お手数ですが、ローカルのリポジトリ設定変更お願い致します！
